### ISSUE TITLE
While installing dotfix, the installation script should also see whether there is already same Dot fix preinstalled or not.

### ISSUE THREAD

**Issue by PranavBhattarai** [nipunnarang/oneplusdotfix#1]
I use stable official Pixel Experience 10 ROM on OnePlus 5. 

OTA updates this OS comes in each week or two. 

According to OS maintainer, **Dot Fix** is preinstalled in the OS. I haven't asked him about the "Pixel color" profile.

But I have some doubts, so I flashed Dotfix & Pixel-Color using Magisk. 

Now my concern is why these Magisk zips/modules, doesn't recognize the same camera Dot fix and same Pixel profile **if they already exist**. It should have recognized it. By doing this, it would have made things more comfortable for end-users like me.

Why reinstall the same thing? There should be a verbose telling user somthing about old dotfix.

These are my log files:

[oneplusdotfix-debug.log](https://github.com/Magisk-Modules-Repo/oneplusdotfix/files/4129058/oneplusdotfix-debug.log)
[pixel2colours-debug.log](https://github.com/Magisk-Modules-Repo/oneplusdotfix/files/4129059/pixel2colours-debug.log)

**Comment by shadowstepxda** [comment]
If you are unsure whether the ROM includes the modified libraries from DotFix, you should just go ahead and install the module, it will overwrite the libraries, irrespective of the fact whether the ROM you're using has the modified libraries inbuilt or not.

It is the ROM maintainer's job to know whether he/she has included the modified libraries or not, not the zip's job.
