### ISSUE TITLE
oneplusdotfix make camera can't work

### ISSUE THREAD

**Issue by xuhuan** [nipunnarang/oneplusdotfix#2]
I have some problems when using it。

> Device:
> oneplus 5t
> H2OS 10.0.2

when install this module 
> system camera can't open;
> Google Camera also can't open;
> flashlight can't open;

remove this module,all returned to normal。

**Comment by shadowstepxda** [comment]
The zip doesn't support the newest camera libraries, so it won't work with the latest H2OS.
