### ISSUE TITLE
Will there be an Android 14 update?

### ISSUE THREAD

**Issue by ShoyebOP** [nipunnarang/oneplusdotfix#3]
I'm on lineage os 21(android 14). I'm Just wondering if there wil be an android 14 update or not. If not then I'll just downgrade to lineage os 20.

**Comment by Kixero** [comment]
Changing only the MAXAPI variable to 34 in the customize.sh seems to have worked for me on lineageOS 21. No dots anymore and front camera working.

**Comment by ShoyebOP** [comment]
> Changing only the MAXAPI variable to 34 in the customize.sh seems to have worked for me on lineageOS 21. No dots anymore and front camera working.

Thanks it really worked.

**Comment by shadowstepxda** [comment]
Closing this off as the release is just around the corner. :)
